### ISSUE TITLE
[BUG] 이미 친구인 유저에게 친구요청 가능 + 본인에게 친구요청 가능 버그 해결하기

### ISSUE THREAD

**Issue by m48483** [encore-full-stack-5/bootjar_TODO_FE#68]
완전 대박 버그;;;;

- [x] #69
- [x] #70

**Comment by m48483** [comment]
![image](https://github.com/encore-full-stack-5/bootjar_TODO_FE/assets/71882579/24ee94f9-36c5-4c1e-ba5f-9fddca223a3d)
나는 나와 친구한다

**Comment by ParkMiram** [comment]
?
